### ISSUE TITLE
Support of xml comments

### ISSUE THREAD

**Issue by ralemy** [nfarina/xmldoc#22]
I am trying to use this library to keep track of version dependency of pom files. (by the way it is awesome and thank you very much for sharing it). The only problem I have is that the comments will be stripped of the original file once I use toString() to write it back to the disk.

Looking at the code I don't see the oncomment event being captured. is this by design, or is there another way to capture comments?

Regards,
Reza

**Comment by nfarina** [comment]
Hi Reza, I'd say the current behavior is "design-by-omission". xmldoc was not really intended to allow you to modify XML and write it back to disk - the toString() method is only meant for debugging. In order to support comments we'd have to introduce a new XML node type which would move this library away from the "simple XML parser" that it's meant to be.

Perhaps you could try parsing your XML using a more full-featured library like [elementtree](https://github.com/racker/node-elementtree)?

**Comment by nfarina** [comment]
Changed my mind on this. Thanks for the request!
